# Generated by Django 4.2.2 on 2023-06-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_film', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='filmconfig',
            options={'ordering': ('-created_at',)},
        ),
    ]
