# Generated by Django 4.2.2 on 2023-06-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_film', '0002_alter_category_options_alter_film_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_trailer',
            field=models.FileField(default='simple_film/films/2023/06/12/The.Man.Who.Knew.Infinity.2015.BDRip.1080p.ukr_720.mp4', upload_to='simple_film/films_trailer/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
