# Generated by Django 4.2.2 on 2023-06-16 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_film', '0003_film_film_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='simple_film/images/%Y/%m/%d/', verbose_name='Film Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_images_set', to='simple_film.film')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
