# Generated by Django 4.2.2 on 2023-06-17 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_film', '0004_filmimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmRetrieveView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_retrieve_view_set', to='simple_film.film')),
            ],
        ),
    ]
