# Generated by Django 4.2.2 on 2023-06-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_film', '0005_filmretrieveview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmretrieveview',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='filmretrieveview',
            name='ip_info',
            field=models.JSONField(default=dict),
        ),
    ]
